pipeline {

    agent any
 	parameters {
        string(defaultValue: "natasha.vasdev@oracle.com", description: 'What environment?', name: 'EmailRecipient')
        // choices are newline separated
        choice(choices: 'US-EAST-1\nUS-WEST-2', description: 'What AWS region?', name: 'region')
    }
    tools {
        maven 'maven'
        jdk 'jdk1.8'
    }
    stages {
        stage ('Checkout'){
            steps {
            checkout scm
			
            }
   	    }
        stage('Build') {
            steps {
	       sh "echo ${params.EmailRecipient}"
	       sh "echo ${params.region}"    
               sh 'mvn clean package sonar:sonar -Dsonar.host.url=http://dhcp-10-180-42-232.in.oracle.com:9000/ -DproxySet=true -DproxyHost=www-proxy.us.oracle.com -DproxyPort=80'
		  //sh 'mvn clean package -DproxySet=true -DproxyHost=www-proxy.us.oracle.com -DproxyPort=80'
		   	nexusArtifactUploader(
    			nexusVersion: 'nexus3',
    			protocol: 'http',
    			nexusUrl: 'dhcp-10-180-42-232.in.oracle.com:8081',
    			groupId: 'com.mkyong',
    			version: '1.0-SNAPSHOT',
    			repository: 'maven-snapshots',
    			credentialsId: 'eb698352-3801-4665-8314-10acd9ab6874',
    			artifacts: [
        		[artifactId: 'CounterWebApp',
         		classifier: '',
         		file: 'CounterWebApp/target/CounterWebApp.war',
         		type: 'war']
    			]
 		)
           
   	    }
            
        }
		
		stage ('success'){
            steps {
                script {
                    currentBuild.result = 'SUCCESS'
                }
            }
        }
		
    }
	post {
        failure {
            script {
                currentBuild.result = 'FAILURE'
            }
        }

        always {
            step([$class: 'Mailer',
                notifyEveryUnstableBuild: true,
                recipients: "${params.EmailRecipient}",
                sendToIndividuals: true])
        }
    }
}
