pipeline {

 

    agent any

               parameters {

        string(defaultValue: "", description: 'What environment?', name: 'Environment')

        // choices are newline separated

        choice(choices: 'US-EAST-1\nUS-WEST-2', description: 'What AWS region?', name: 'region')

    }

    tools {

        maven 'Maven'

        jdk 'Jdk1.8'

    }

    stages {

        stage ('Checkout'){

            steps

                                                {

                                                                git (

                                                                                url: 'https://github.com/nvasdev/DevOps.git',

                                                                                credentialsId: '9b64ea1f-080a-4bea-adb4-6ac777022e3a'

                                                                )

                                                }

                                               

            }

                               

    }

}
